sudo: required

language: cpp

compiler:
    - gcc
    - clang

services:
    - docker

env:
    - TEST_OS=fedora-latest
    - TEST_OS=ubuntu-rolling
    - TEST_OS=ubuntu-latest

before_install:
    - docker build -t icecream-sundae-$TEST_OS -f .travis/$TEST_OS/Dockerfile .

script:
    - docker run --rm icecream-sundae-$TEST_OS /bin/sh -c "CC=$CC CXX=$CXX
        meson -Dwerror=true -Db_sanitize=address,undefined .. &&
        ninja &&
        ninja test &&
        ninja install"
