sudo: required

language: cpp

services:
    - docker

env:
    - TEST_OS=fedora-latest
    - TEST_OS=ubuntu-rolling
    - TEST_OS=ubuntu-latest

before_install:
    - docker build -t icecream-sundae-$TEST_OS -f .travis/$TEST_OS/Dockerfile .

script:
    - docker run icecream-sundae-$TEST_OS /bin/sh -c "CC=$CC CXX=$CXX
        meson .. &&
        ninja &&
        ninja test &&
        ninja install"
